version: "3.8"

services:
  mongo:
    image: mongo:6
    container_name: mongodb
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - ./mongo-data:/data/db

  api:
    build: .
    container_name: oficina-api
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/oficina
